dataset_config:
  vizwiz:
    return_features_info: true
    processors:
      # Stop fasttext from loading by overriding the context_processor
      context_processor:
        type: simple_word
        params: {}
      text_processor:
        type: bert_tokenizer
        params:
          tokenizer_config:
            type: bert-base-uncased
            params:
              do_lower_case: true
          mask_probability: 0
          max_seq_length: 128
      transformer_bbox_processor:
        type: transformer_bbox
        params:
          bbox_key: bbox
          image_width_key: image_width
          image_height_key: image_height
