includes:
  - configs/datasets/hateful_memes/bert.yaml
  - configs/datasets/visual_entailment/defaults.yaml

model_config:
  concat_bert_tutorial:
    classifier_a:
      type: mlp
      params:
        num_layers: 2
    classifier_b:
      type: mlp
      params:
        num_layers: 2
    losses:
      - type: cross_entropy

scheduler:
  type: warmup_linear
  params:
    num_warmup_steps: 2000
    num_training_steps: ${training.max_updates}

optimizer:
  type: adam_w
  params:
    lr: 5e-5
    eps: 1e-8

evaluation:
  metrics:
    - accuracy
    - binary_f1
    - roc_auc

training:
  batch_size: 2
  lr_scheduler: true
  max_updates: 22000
  early_stop:
    criteria: hateful_memes/roc_auc
    minimize: false

multitasking:
  enabled: true
  type: ratios
  params:
    sampling_ratios:
      visual_entailment: 0.5
      hateful_memes: 0.5